######## Using Travis as Test Suite #######
language: generic

#specify admin access
sudo: required

#specify programs to run
sevices:
    - docker

before_install:
    #specify file for test image build
    - docker build -t macshild/nginx-static-serve-up-test -f Dockerfile.dev .  

#specify instructions for running test suite container
script:
   # - docker run macshild/nginx-static-serve-up-test npm run test -- --coverage
    - docker run -e CI=true macshild/nginx-static-serve-up-test npm run test


######## Using Travis CI to Deploy to Elastic Beanstalk ########
deploy:
    ##fix for missing bucket_name error
    edge: true

    #specify name of hosting service
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "Nginx Static Serve-up"
    env: "NginxStaticServeUp-env"

    #specify bucket containing zip file of  code uploaded by travis to be redeploy by AWS.
    bucket_name: "elasticbeanstalk-us-east-1-972707242260"

    #specify dir in bucket containing app files
    #use app name for a frist time scenario
    bucket_path: "Nginx Static Serve-up"

    on:
        #specify branch in codebase to triger deploy
        branch: master

    #specify api keys that grants travis access to AWS
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    #secret_access_key:
        #secure: "$AWS_SECRET_KEY"
